### ISSUE TITLE
User Stories

### ISSUE THREAD

**Issue by MatthewKaplan** [MatthewKaplan/yoga-fee-finder#2]
User Story 1: As a user I should be able to find a yoga studio based on my experience (Beginner or Advanced)

User Story 2: As a user I should be able to display yoga studios from lowest price to highest price.

User Story 3: As a user I should be able to see the google rating of the yoga studio that I’m interested in.

User Story 4: As a user I should be able to filter yoga studios based on the type of yoga they offer. 

User Story 5: As a user I should be able to see if a studio offers teacher training.

User Story 6: As a user I should be able to read the studio mission statement.

User Story 7: As a user I should be able to navigate to the yoga studios website to get more information.

User Story 8: As a user I should be able to easily find the location of each yoga studio.

User Story 9: As a user I should be able to easily find the number to contact each yoga studio.

User Story 10: As a user I should be able to search for studios by their name.

**Comment by SallyHaefling** [comment]
Sent to instructors. Completed.
